# This is a basic workflow to help you get started with Actions

name: Portfolio

# Controls when the workflow will run
on:
  # "master" 브랜치에 푸시할때마다 워크플로우 트리거
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # GITHUB_TOKEN을 사용하는 작업 내의 액세스를 추가하거나 제거
    permissions:
      # 작업이 릴리스를 만들 수 있도록 허용
      contents: write
    
    # 동일한 동시성 그룹을 사용하는 단일 작업 또는 워크플로우만 한 번에 실행
    concurrency:
      # 여러 워크플로우가 있는 경우 다른 워크플로우의 작업이 취소되지 않도록 동시성 그룹을 빌드
      group: ${{ github.workflow }}-${{ github.ref }} 
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # node.js 20.16 사용
      - uses: actions/setup-node@v3
        with:
          node-version: 20.16
      
      # npm install 보다 빠른 npm ci로 빌드 및 테스트
      - run: npm ci 
      - run: npm run build

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}     
          # 배포할 디렉토리 이름 (꼭 확인!)
          publish_dir: ./build
